services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin: 
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    user: "${UID}:${GID}"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - pg-database

volumes:
    ny_taxi_postgres_data:
      external: true
    pgadmin:
      external: true

env_file:
  - database.env